/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ufpso.estructuras;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author anderson
 */
public class Main extends javax.swing.JFrame {    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }
    
    Cinema cinema;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _lblCine = new javax.swing.JLabel();
        btnSellTickets = new javax.swing.JButton();
        btnSellReport = new javax.swing.JButton();
        btnSellCheck = new javax.swing.JButton();
        btnShowClients = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        _lblCine.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        _lblCine.setText("Cine");

        btnSellTickets.setText("Vender boletas");

        btnSellReport.setText("Reporte de compras");

        btnSellCheck.setText("Comprobar venta");

        btnShowClients.setText("Mostrar compradores");
        btnShowClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowClientsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSellTickets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShowClients, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSellCheck, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSellReport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(_lblCine)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(_lblCine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnSellTickets)
                .addGap(18, 18, 18)
                .addComponent(btnSellReport)
                .addGap(18, 18, 18)
                .addComponent(btnSellCheck)
                .addGap(18, 18, 18)
                .addComponent(btnShowClients)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowClientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowClientsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main mainFrame = new Main();
                
                String movieName = JOptionPane.showInputDialog(mainFrame, "Nombre de la película:");
                if (movieName.isBlank()) {
                    JOptionPane.showMessageDialog(mainFrame, "El nombre no puede estar vacío.");
                    return;
                }
                
                int isAdultMovieRaw = JOptionPane.showConfirmDialog(mainFrame, "¿Es película para adultos?", "¿Pueden entrar menores de 14 años?", JOptionPane.YES_NO_OPTION);
                boolean isAdultMovie = false;
                if (isAdultMovieRaw == 0) {
                    isAdultMovie = true;
                }

                String ticketsRaw = JOptionPane.showInputDialog(mainFrame, "¿Cuántas boletas hay disponibles?");
                int tickets;
                try {
                    tickets = Integer.parseInt(ticketsRaw);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(mainFrame, "Debe ser un número entero.");
                    return;
                }
                
                mainFrame.cinema = new Cinema(movieName, isAdultMovie, tickets);
                mainFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _lblCine;
    private javax.swing.JButton btnSellCheck;
    private javax.swing.JButton btnSellReport;
    private javax.swing.JButton btnSellTickets;
    private javax.swing.JButton btnShowClients;
    // End of variables declaration//GEN-END:variables
}
